params:
  app_name : "mlops-sagemaker"
  execution_role_arn : 'arn:aws:iam::259768221514:role/mlops-sagemaker-role-123'
  image_ecr_url : "966180254834.dkr.ecr.ap-south-1.amazonaws.com/mlflow-pyfunc:1.23.1"
  region : "ap-south-1"
  s3_bucket_name : "mlops-demo-123"
  experiment_id : "0"
  run_id : "25bd95371e2343c2a65947ebc20ad9ec"
  model_name : "model"